import inator
print("Thank you for using ClassJoinInator")
print("Initiated automation software...")
a1 = inator.Automate()
print("Trying to login...")
a1.login()
print("Login Confirmed.....")
print("Searching for available classes...")
a1.find_classes()
print("Trying to join the most recently opened class (if any)...")
a1.join_most_recent_class()
print("Have a nice day 😊")
